### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by oleole39** [comment]
You don't like the more self-explanatory full app name :) ?

Why `sso="false"` instead of `not_relevant` ? I mean it doesn't make any difference to me, but would it be in order to deprecate the not_relevant param ? Or in which case could `not_relevant` actually be "relevant" ?

`[resources.ports]` is not necessary when leaving default config ?

**Comment by ericgaspar** [comment]
> You don't like the more self-explanatory full app name :) ?

The linter doesn't like the more self-explanatory full app name


> Why `sso="false"` instead of `not_relevant` ? I mean it doesn't make any difference to me, but would it be in order to deprecate the not_relevant param ? Or in which case could `not_relevant` actually be "relevant" ?

Did we already had this conversation?

> [resources.ports] is not necessary when leaving default config ?

If the app does not need port, why set up a port?

**Comment by oleole39** [comment]
> The linter doesn't like the more self-explanatory full app name

Uh right, do you know max app name lenght ? Would `Mastodon Archive Reader Lite` (without the brackets) be too long as well ?  

> > Why `sso="false"` instead of `not_relevant` ? I mean it doesn't make any difference to me, but would it be in order to deprecate the not_relevant param ? Or in which case could `not_relevant` actually be "relevant" ?
> 
> Did we already had this conversation?

Hmm I guess you refer to https://github.com/YunoHost-Apps/pinkarrows_ynh/pull/37, still something isn't clear to me as in my last question there (although I am better inspired by your answer today). For apps which get executed exclusively client-side, could there be cases where it would be interesting to have SSO & LDAP on `true` ? Maybe one could still be willing to put the app behind SSO (let's say if app was shipping a confidential data set), but as for LDAP I can't imagine a use case in this situation?

> > [resources.ports] is not necessary when leaving default config ?
> 
> If the app does not need port, why set up a port?

Ok, I thought maybe that was needed so that file were granted access on the webserver via port 80 or so...

**Comment by oleole39** [comment]
> do you know max app name lenght ?

23 chars

**Pull request merged**
